include: package:very_good_analysis/analysis_options.yaml

analyzer:
  enable-experiment:
    - macros
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  language:
    strict-raw-types: true
  errors:
    public_member_api_docs: ignore
    one_member_abstracts: ignore
    avoid_equals_and_hash_code_on_mutable_classes: ignore
    use_string_in_part_of_directives: ignore
    use_setters_to_change_properties: ignore
    implements_repeated: ignore
    use_to_and_as_if_applicable: ignore
